//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int AccountID { get; set; }
        public Nullable<decimal> Withdrawl { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public System.DateTime Time { get; set; }
        public string Type { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
